# Exercice 1

- Create a numpy array from the following list [11.7, 20, 325, 10.2, 11.7, 20]
- Replace the first 11.7 by 5
- Replace all 20 by 0
- Compute the size in memory
- Change the type to uint8
- What is the size of the array
- Check the values, did something happen ?

# Exercice 2

- Create a numpy array with the following matrix : [[1, 2, 3],  [4, 5, 6], [7, 8, np.nan]]
- Show :
    - The type of data in the matrix
    - the shape of that matrix
    - the number of dimensions
    - The number of elements
- Multply the last column by 5 and divide the first line by 0
- Change the type to int, what happened ?

# Exercice 3

Exercice:
1. Create the matrix in the variable x1
  ```py
      [[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]]
````

2. Extract part of x1 int the variable x2
  ```py
      [[50, 60],
       [80, 90]]
````
3. Relace the 50 de x2 by 99
4. Show x1

# Exercice 4

Exercice:
1. Create the matrix x3:
  ```py
      [[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]]
````

2. Extract a __copy__ of some values of x3 into variable x4
  ```py
      [[50, 60],
       [80, 90]]
````
3. Replace 50 in x4 by 99
4. SHow the values in x3

# Exercice 5

- Create a matrix (4,4) filled with random values between 2 and 8
- Create an identity matrix, try multiple solutions.
- Create a matrix where the diagonal is filled with 6 random values

(tip: 'zeros','identity', 'fill_diagonal')

# Exercice 6

- Reproduce this matrix (without the name for the lines/columns)
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>pâtes</th>
      <th>légumes</th>
      <th>divers</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>bob</th>
      <td>10€</td>
      <td>30€</td>
      <td>5€</td>
    </tr>
    <tr>
      <th>alice</th>
      <td>20€</td>
      <td>50€</td>
      <td>1€</td>
    </tr>
    <tr>
      <th>john</th>
      <td>15€</td>
      <td>30€</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>

- Show the total amount of buying
- Show the total amount per person
- Show the mean value by type of item

# Exercice 7

This time we have the quantity and the unit price

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>pâtes</th>
      <th>légumes</th>
      <th>divers</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>bob</th>
      <td>1</td>
      <td>4</td>
      <td>2</td>
    </tr>
    <tr>
      <th>alice</th>
      <td>3</td>
      <td>5</td>
      <td>7</td>
    </tr>
    <tr>
      <th>john</th>
      <td>5</td>
      <td>4</td>
      <td>4</td>
    </tr>
  </tbody>
</table>

unit price
```py
[20, 5, 3]
````

- What is the total amount per person
- What is the total amount per product